#ifdef CONFIG_DYNAMIC_DEBUG
    #define DEBUG_HASH 1
    #define DEBUG_HASH2 2
#endif

#define AUTOCONF_INCLUDED

#define OBJTREE ""
#define SRCTREE ""

#define KBUILD_STR(s) #s

//Non-boolean features
#define CONFIG_X86_L1_CACHE_SHIFT 5
#define CONFIG_X86_INTERNODE_CACHE_SHIFT 5
#define CONFIG_IO_DELAY_TYPE_0X80 0
#define CONFIG_IO_DELAY_TYPE_0XED 1
#define CONFIG_DEFAULT_IO_DELAY_TYPE 0
#define CONFIG_IO_DELAY_TYPE_NONE 3

#define CONFIG_HZ 250
#define HZ 250

#define CONFIG_X86_MINIMUM_CPU_FAMILY 5

#undef ACPI_CUSTOM_DSDT //triggers invalid include otherwise

#define CONFIG_NODES_SHIFT 32
#define CONFIG_PGTABLE_LEVELS 5
#define NR_CPUS 4
#define CONFIG_RCU_FANOUT_LEAF 16
#define BITS_PER_LONG 64
#define GFP_ZONES_SHIFT 2


#define SECTION_SIZE_BITS 27
#define MAX_PHYSADDR_BITS 44
#define MAX_PHYSMEM_BITS 46
#define SECTIONS_SHIFT 19
#define SECTIONS_WIDTH 19
#define ZONES_WIDTH 0
#define ZONES_SHIFT 0
#define MAX_NR_ZONES 1
#define NODES_SHIFT 0
#define NR_PAGEFLAGS 1